---
name: Math-SymbolicX-Calculator
version: 0.01
author:
  - 'Steffen Mueller <smueller@cpan.org>'
abstract: A representation of a Symbolic Calculator
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Math::Symbolic: 0.501
  Math::Symbolic::Custom::Transformation: 1.24
  Params::Util: 0
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.0
  Test::Pod::Coverage: 1.0
provides:
  Math::SymbolicX::Calculator:
    file: lib/Math/SymbolicX/Calculator.pm
    version: 0.01
  Math::SymbolicX::Calculator::Command:
    file: lib/Math/SymbolicX/Calculator/Command.pm
    version: 0.01
  Math::SymbolicX::Calculator::Command::Assignment:
    file: lib/Math/SymbolicX/Calculator/Command/Assignment.pm
    version: 0.01
  Math::SymbolicX::Calculator::Command::DerivativeApplication:
    file: lib/Math/SymbolicX/Calculator/Command/DerivativeApplication.pm
    version: 0.01
  Math::SymbolicX::Calculator::Command::Insertion:
    file: lib/Math/SymbolicX/Calculator/Command/Insertion.pm
    version: 0.01
  Math::SymbolicX::Calculator::Command::Transformation:
    file: lib/Math/SymbolicX/Calculator/Command/Transformation.pm
    version: 0.01
  Math::SymbolicX::Calculator::Interface:
    file: lib/Math/SymbolicX/Calculator/Interface.pm
    version: 0.01
generated_by: Module::Build version 0.280501
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
